pipeline {
    agent any
    stages {
        stage ('Compile Stage') {
            steps {
                  withMaven(maven : 'maven_3_6_0') {
                      'mvn clean compile'
                  }
            }
        }
        stage ('Testing Stage') {
            steps {
                  withMaven(maven : 'maven_3_6_0') {
                      'mvn clean test'
                  }
            }
        }
        stage ('Deployment Stage') {
            steps {
                  withMaven(maven : 'maven_3_6_0') {
                      'mvn deploy'
                  }
            }
        }
    }
}
